name: testing
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  mb_button: ^1.0.3
  cupertino_icons: ^1.0.2
  google_fonts: ^2.3.1
  intl: ^0.17.0
  overlay_support: ^2.0.0
  connectivity_plus: ^2.2.1
  dcdg: ^4.0.1
  line_icons: ^2.0.1
  package_info_plus: ^1.4.2
  url_launcher: ^6.1.0
  provider: ^6.0.3
  shared_preferences: ^2.0.15
  draggable_scrollbar: ^0.1.0
  flutter_native_splash: ^2.2.3+1
  flutter_launcher_icons: ^0.9.3
  rename: ^2.0.1
flutter_native_splash:
  #color: "#FFFFFF"
  background_image: assets\background.png
  image: assets\app_logo.png
  android: true
  ios: true
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_icons:
  image_path: "assets/app_logo.png"
  android: true
  #flutter pub run flutter_launcher_icons:main

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/event_icons/