@startuml
set namespaceSeparator ::

class "testing::main.dart::MyApp" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "testing::main.dart::MyApp"

class "testing::main.dart::MyHomePage" {
  +MyHomePageState createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "testing::main.dart::MyHomePage"

class "testing::main.dart::MyHomePageState" {
  -String _timeString
  +TextEditingController editingController
  -List<Map<String, dynamic>> _allUsers
  -List<Map<String, dynamic>> _foundUsers
  +void runFilter()
  +void initState()
  -void _getTime()
  -String _formatDateTime()
  +Future<void> selectDate()
  +Widget build()
}

"testing::main.dart::MyHomePageState" o-- "flutter::src::widgets::editable_text.dart::TextEditingController"
"flutter::src::widgets::framework.dart::State" <|-- "testing::main.dart::MyHomePageState"

class "testing::network.dart::Troubleshoot" {
  +_TroubleshootState createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "testing::network.dart::Troubleshoot"

class "testing::network.dart::_TroubleshootState" {
  +void initState()
  +void dispose()
  +Widget build()
}

"flutter::src::widgets::framework.dart::State" <|-- "testing::network.dart::_TroubleshootState"


@enduml